### ISSUE TITLE
storyboard 내 특정 뷰를 UINib으로 로드하는 방법 찾기

### ISSUE THREAD

**Issue by kjoonk** [codesquad-member-2020/issue-tracker-04#10]
### 알아오기

- [ ] `testConfigureIssueListDataSource` 메소드 `IssueCell` label의 text 테스트 방법 알아보기

(nib을 통해 Cell을 생성하는 방법 찾기)

_Originally posted by @dev-Lena in https://github.com/codesquad-member-2020/issue-tracker-04/issues/5#issuecomment-641129154_

**Comment by kjoonk** [comment]
좀 찾아봤어요.

알고 있듯이 `TableView.register()`는 nib 또는 cellClass 방식이 있죠. 
우리는 storyboard에서 작성한 prototype cell를 사용해야 하니 nib 방식으로 등록해야 해요. 
즉 `IssueCell`을 nib 형태로 변환해야 하는 거죠.

그런데 storyboard 파일을 로드할 때 뷰컨트롤러 단위로 nib 파일을 생성하는 것 같아요. 

```zsh
$ cd ~/Library/Developer/CoreSimulator/Devices/12C45B27-97B3-484A-8315-5D40BBE94CB9/data/Containers/Bundle/Application
$ tree
.
└── F993F245-F571-4E1E-A7AA-3C424DB2C89F
    ├── BundleMetadata.plist
    └── IssueTracker.app
        ├── Base.lproj
        │   ├── LaunchScreen.storyboardc
        │   │   ├── 01J-lp-oVM-view-Ze5-6b-2t3.nib
        │   │   ├── Info.plist
        │   │   └── UIViewController-01J-lp-oVM.nib
        │   └── Main.storyboardc
        │       ├── BYZ-38-t0r-view-8bC-Xf-vdC.nib
        │       ├── Info.plist
        │       ├── IssueDetailViewController.nib
        │       ├── IssueListViewController.nib
        │       └── Z9y-Eb-3RU-view-2XL-x3-hZi.nib
        ├── Frameworks
```

시뮬레이터 실행시켰을 때 생성된 앱 경로인 것 같아요(에러 메시지에서 알게 됨). `Main.storyboardc` 폴더를 보면 ViewController 밖에 없어요. 파일명이 id 형태로 돼 있는 파일은 뷰 컨트롤러의 Object ID랑 같아요.

그러니, 현재로선 nib 파일 내에서 view를 추출하는 방법을 찾지 않는 한 힘들지 않을까 싶네요. 😓
아니면 IssueCell을 xib 파일로 만든다면 가능하겠지요.

**Comment by dev-Lena** [comment]
와우! 감사합니다!🌻
그럼 원활한 테스트를 위해 본래 코드에 xib 파일을 추가해야할까요?? 테스트를 위해 코드를 수정해가면서 테스트가 가능한 코드로 개선하는게 좋을지 아니면 원래 코드를 테스트하기 위한 더 나은 방법을 찾는게 좋을지 얘기해봐요!
