### ISSUE TITLE
Jack의 기존 issueTracker에 대한 질문

### ISSUE THREAD

**Issue by sigridjineth** [codesquad-member-2020/issue-tracker-04#107]
### 기존 issueTracker에 대한 질문
- 두 관계 중 관계의 주인은 누구인가? (마일스톤과 이슈)
- 원래는 ```@ManyToOne```인 이슈가 주인이지만 아래 설계는 중간 테이블을 만드는 설계이기 때문에 누가 주인인지 헷갈린다.
```java
//Milestone.java
@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
@JoinColumn(name = "milestone_id", nullable = true)
private Milestone milestone;
```
```java
//Issues.java
@JsonIgnore
@OneToMany(fetch = FetchType.LAZY, orphanRemoval = true, cascade = CascadeType.ALL)
@LazyCollection(LazyCollectionOption.FALSE)
@JoinTable(
	name = "milestone_has_issue",
	joinColumns = @JoinColumn(name = "milestone_id"),
	inverseJoinColumns = @JoinColumn(name = "issue_id")
)
private List<Issue> issues = new ArrayList<>();
```

**Comment by realsigridjin** [comment]
사실 연관관계의 주인은 항상 N측 테이블이어야 합니다. 다시 말해서, 마일스톤 하나에 이슈 여러 개가 매핑된다면 당연히 이슈가 연관관계의 주인으로 됩니다. 아시다시피 테이블의 외래키를 관리하는 쪽이 주인이 되어야 하고, 주인이 아닌 쪽은 읽기만 할 수 있죠. 우리는 단방향 관계 2개만 엮었고 이를 양방향으로 연결하지 않았기 때문에(joinColumn과 mappedBy를 통해 주인을 지정하지 않았죠) 연관관계의 주인이 없다고 말할 수 있습니다. 지난 프로젝트에는 일대다 다대일 단방향으로 구현했는데, 사실 양방향 관계로 구현하는 것이 좋다고 합니다.

* 아래 글도 읽어보세요.
https://homoefficio.github.io/2019/04/28/JPA-%EC%9D%BC%EB%8C%80%EB%8B%A4-%EB%8B%A8%EB%B0%A9%ED%96%A5-%EB%A7%A4%ED%95%91-%EC%9E%98%EB%AA%BB-%EC%82%AC%EC%9A%A9%ED%95%98%EB%A9%B4-%EB%B2%8C%EC%96%B4%EC%A7%80%EB%8A%94-%EC%9D%BC/

* 브라이언 리뷰에도 유사한 내용이 있었습니다.
https://github.com/codesquad-member-2020/issue-tracker-04/pull/103

* 아래 글도 읽어보시구요.
https://www.notion.so/JPA-Best-Practice-a4f778e82f2444719a2a49d35d89ea56

**Comment by guswns1659** [comment]
네네 섬세한 피드백 감사합니다. 
jpa를 공부하면서 우리 프로젝트를 다시 생각하고 있는데 좋네요! 
최대한 양방향 매핑을 하는 것은 좋지만 cascade 전략, fetch 전략 등 잘 알고 쓰면 좋겠네요.
