### ISSUE TITLE
이슈 모델 필터 

### ISSUE THREAD

**Issue by kjoonk** [codesquad-member-2020/issue-tracker-04#13]
## Issue 모델 상태 추가
- [x] open/closed
- synced(나중에)

## 목록에 있는 이슈 필터
- [x] 관련 메소드 추가

### 열린 이슈들
- 이슈의 상태가 open인 것들

### 내가 작성한 이슈들
- 이슈의 작성자(author)가 사용자인 이슈들 & open

### 나한테 할당된 이슈들
- assignee가 사용자인 이슈들 & open

### 내가 댓글을 남긴 이슈들
- 댓글의 작성자가 사용자인 이슈 & open

### 닫힌 이슈들
- 이슈의 상태가 closed인 이슈들

**Comment by dev-Lena** [comment]
현재 상태까지 구현 완료되어 클로즈하겠습니다!
