### ISSUE TITLE
Unwind Segue 사용법

### ISSUE THREAD

**Issue by kjoonk** [codesquad-member-2020/issue-tracker-04#18]
## Unwind Segue
A -> B로 전환할 때 segue로 연결하듯이, B -> A로 다시 돌아갈 때 사용하는 segue.     
button에 ibaction을 쓰는 대신에 unwind segue를 사용하면 된다. 
`prepare(for:sender:)`, `shouldPerformSegue(withIdentifier:sender:)` 메소드를 그대로 사용할 수 있다.

[공식문서](https://developer.apple.com/documentation/uikit/resource_management/dismissing_a_view_controller_with_an_unwind_segue)
[참고](https://medium.com/@kyeahen/ios-unwind-segue-in-swift-e8ff0e7fbbcd)

## 사용법
B -> A viewController로 돌아갈 때

1. VC A(목적지)에 @IBAction method 작성
2. storyboard에서 버튼을 exit로 ctrl 드래그
3. 만들어 놓은 ibaction method에 연결

#### B 뷰컨트롤러
1. tap button
1. `shouldPerformSegue(withIdentifier:sender:)`
1. trigger segue
1. `prepare(for:sender:)`

#### A 컨트롤러
1. ibaction method
1. `viewWillAppear(_:)`

**Comment by kjoonk** [comment]
@dev-Lena

**Comment by dev-Lena** [comment]
모스가 어제 설명해준 것과 문서를 읽어보고 정리한 점을 남겨봤어요!🤓
감사합니다! 😃

### Segue와 Unwind Segue의 차이점
1. 뷰 컨트롤러를 present할 때 사용하는 segue와 달리  unwind segue는 뷰 컨트롤러를 dismiss 할 때 사용. 
2. segue와 달리 현재 뷰 컨트롤러가 사라지고 나서 어디로 전환될지 특정한 타겟(뷰 컨트롤러)을 스토리보드에서 화살표로(?) 지정하지 않음. 

### 신기했던 점
1. 어느 화면으로 전환될지 특정하지 않는 대신에 unwind segue action 메소드가 있는 뷰 컨트롤러가 unwind segue의 잠재적 도착지가 될 수 있다는 점.
2. 스토리 보드에서 unwind segues를 설정해주기 전 최소 하나의 뷰 컨트롤러에 action 메소드를 추가해야한다는 점 그렇지 않으면, Xcode에서 에러가 난다는 점. 
3. 하지만 action 메소드만 존재한다면 그 메소드에서 아무것도 하지 않아도 된다는 점. (이 점이 공식 문서에 명시 되어있는 것도 신기했음)
4. action 메소드에서 dismiss된 뷰 컨트롤러의 데이터를 도착지 뷰 컨트롤러에 전달하는데에 사용할 수 있다는 점.
5. 지금까지 뷰 컨트롤러간 데이터 전달을 할 때는 segue와 Delegate, notification을 사용했었는데 이 외에 unwind Segue라는 방법이 있다는 점!!

### 이번 프로젝트에서 유용할 것 같은 점
1. 이슈를 추가하는 화면과 수정하는 화면이 같은데 
이슈 추가 화면으로 사용할 때는 추가 후 이슈 목록 화면으로 돌아가고, 
이슈 수정 화면으로 사용할 때는 수정 후 이슈 상세 화면으로 돌아갈 때 사용하면 유용할 것 같아요!
2. 화면을 dismiss하고 데이터를 다음 화면에 전달해야할 때 유용할 것같습니다!
