### ISSUE TITLE
네트워크 요청 처리 구조

### ISSUE THREAD

**Issue by kjoonk** [codesquad-member-2020/issue-tracker-04#25]
- URLSession 사용
- Endpoint URL 따로 관리

**Comment by dev-Lena** [comment]
네트워크 관련 참고자료입니다!
[네트워크 참고자료 by JK](https://github.com/godrm/swift-pokergameapp/tree/Network)
[Result Type](https://developer.apple.com/documentation/swift/result)

**Comment by kjoonk** [comment]
만들었어요. 간단히 설명하면

- Endpoint: `URL`을 만들수 있어요. 경로와 쿼리를 조합할 수 있어요.
- NetworkManager: `Result`를 적용했어요. 사용하는 쪽에서 `switch`나 `if` 문으로 제어를 하면 돼요.

더 다듬어야겠어요. 실제로 적용하면서 개선할래요. 😅
