### ISSUE TITLE
이슈 목록 수정 모드 리팩토링

### ISSUE THREAD

**Issue by dev-Lena** [codesquad-member-2020/issue-tracker-04#38]
### 이슈 목록의 상태
: normal,  edit(isSelected: true), edit(isSelected: false)

### 리팩토링 체크 사항

- [x] 메소드 중복 제거
- [x] 연산 프로퍼티 -> 프로퍼티로 수정
- [x] Enum으로 IssueListState 상태관리
- ~~[ ] Enum / Struct / Switch로 UIBarButtonItem을 관리 (팩토리)~~
- ~~[ ] NavigationController 클래스 생성 (네비게이션바 버튼과 툴바 버튼 역할 옮기기)~~
- ~~[ ] NavigationController 이벤트 발생시 -> IssueListViewController 알려주기~~
- [x] TableView  Delegate 분리하기

### 클린 코드 확인하기
- [ ] '변수/함수/클래스의 존재 이유/ 수행 기능/ 사용 방법은?' 이 질문에 대답할 수 있도록 네이밍
- [ ] 함수의 들여쓰기 수준은 1단이나 2단을 넘어서지 않는다
- [ ] 한 함수는 한 가지만 하기
  - [ ] 함수 내의 코드를 섹션으로 나눠보기 -> 자연스럽게 나눌 수 없다면 합격!
- [ ] 위에서 아래로 읽을 수 있는 코드 작성 -> 읽어 내려가며 코드 설명할 수 있다면 통과!
- [ ] 함수는 인자를 1개 이하만 갖기

**Comment by dev-Lena** [comment]
@kjoonk 
모스! 오늘 페어프로그래밍 끝나고 추천해주신 'Clean Code (클린 코드,애자일 소프트웨어 장인 정신)'  책을 봤어요! 
오늘 변수와 함수위주로 리팩토링을 해서 목차 중에서 이 부분이랑 관련된 부분을 봤는데 
책에서 얻은 힌트 중에 리팩토링에 적용하면 좋을 점들을 정리해봤어요! (앞으로 적용하려고 노력해볼께요!)

### 네이밍

- 의도를 분명히 밝혀라
    > '변수/함수/클래스의 존재 이유/ 수행 기능/ 사용 방법은?' 이 질문에 대답할 수 있도록 네이밍하기
    > 의미 있는 네이밍인지 확인하기: 주석이 필요하다면 의도를 분명히 드러내지 못했다는 뜻이다!

### 함수
- 작게 만들어라!
    > 함수는 가능한 한 짧게 만들기
    >  if/else/while 문 등에 들어가는 블록은 가능한 한 줄로 만들기 
    > 함수의 들여쓰기 수준은 1단이나 2단을 넘어서지 않게 만들기

- 한 가지만 해라!
    > 함수는 한 가지만 하기
    > 한 함수가 한 가지만 하도록  바꾸기 위해서 먼저
    > 함수 내에서 코드의 역할을 주석으로 남겨보기
    > 의미 있는 이름으로 다른 함수를 추출할 수 있다면 그 함수는 여러 작업을 하는 셈이기 때문에 새로운 함수를 만들어 분리하기
    > 한 가지 작업만 하는지 확인하기 : 한 가지 작업만 하는 함수는 자연스럽게 섹션을 나누기 어렵다!

- 위에서 아래로 읽을 수 있는 코드 작성하기: 내려가기 규칙  ⭐️
    > 코드는 위에서 아래로 이야기처럼 읽혀야 좋은 것을 기억하고 한 함수 다음에는 추상화 수준이 한 단계 낮은 함수가 오도록 하기

- 함수 인수
    > 함수의 인자가 많을수록 함수를 이해하기 어려워지며 갖가지 인수 조합으로 함수를 검증하는 테스트 케이스를 작성하기는 더 어렵다. 따라서 가능하면 입력 인수가 없는 함수를 만들거나 인수가 1개인 함수로 만들기

**Comment by dev-Lena** [comment]
느낀점: 클린 코드?? 열정적으로 적어봤지만 지키기 너무 어렵다... 
다음에 다시 리팩토링을 할 때 고려해보도록하겠습니다!

**Comment by dev-Lena** [comment]
### 수정한 점

- TableView 클래스 분리
- TableViewDelegate 클래스 분리
- IssueState 변경시 알람 : Delegate 사용 (TableView 클래스에서 IssueListViewController로)

### 아직 남아있는 고민점 

- 버튼을 만드는 makeBarButton 메소드의 위치: 분리할 수 있지 않을까...!
- select all, deselect all 메소드는 TableView가 아니라 TableViewDelegate에 있어야 하지 않나?
-> @kjoonk 제 생각에는 결국 TableView의 모든 row에 대해서 선택 표시 또는 비선택 표시를 하는 그리는 영역이기 때문에 Delegate로 옮기지 않고 TableView 클래스에서 해도 된다고 생각하는데 어떠신가요?

**Comment by kjoonk** [comment]
> * select all, deselect all 메소드는 TableView가 아니라 TableViewDelegate에 있어야 하지 않나?
>   -> @kjoonk 제 생각에는 결국 TableView의 모든 row에 대해서 선택 표시 또는 비선택 표시를 하는 그리는 영역이기 때문에 Delegate로 옮기지 않고 TableView 클래스에서 해도 된다고 생각하는데 어떠신가요?

저는 View의 역할이 사용자 입력(액션)을 VC에 전달하고, 그에 대한 결과를 뿌려주는 거라고 생각해서요. 위처럼 직접 사용자 액션을 처리하는 건 좀 어색해 보여요.

**Comment by dev-Lena** [comment]
> > * select all, deselect all 메소드는 TableView가 아니라 TableViewDelegate에 있어야 하지 않나?
> >   -> @kjoonk 제 생각에는 결국 TableView의 모든 row에 대해서 선택 표시 또는 비선택 표시를 하는 그리는 영역이기 때문에 Delegate로 옮기지 않고 TableView 클래스에서 해도 된다고 생각하는데 어떠신가요?
> 
> 저는 View의 역할이 사용자 입력(액션)을 VC에 전달하고, 그에 대한 결과를 뿌려주는 거라고 생각해서요. 위처럼 직접 사용자 액션을 처리하는 건 좀 어색해 보여요.

* 현재 Select All / Deselect All 버튼 처리 과정
1. 사용자 입력(터치 이벤트)을 IssueListViewController의 버튼(Select All / Deselect All)이 감지한다.
2. IssueListViewController에 그 버튼의 Selector 메소드가 있다.
3. 이 Selector 에서 TableView의 메소드를 호출해서 TableView의 모든 row를 선택/비선택 표시해준다.
4. 그리고 TableView 클래스에서 자기가 가지고 있는 Row만큼 TableView.selectRow/deselectRow를 설정해주는 메소드가 있다.

이 과정을 거치고 있는데 이러면 VC에서 받은 버튼의 터치 이벤트에 대한 결과를 TableView 클래스가 처리하는거니까 TableView 클래스가 직접 사용자 액션을 처리하는건 아니지 않나요?? 👀??

**Comment by kjoonk** [comment]
아항 그렇군요. 그렇다면 Lena 의견대로 해도 되겠네요.
