### ISSUE TITLE
필터별 검색을 위한 URL API 제공

### ISSUE THREAD

**Issue by sigridjineth** [codesquad-member-2020/issue-tracker-04#43]

**Comment by realsigridjin** [comment]
filter?status=open&role=authored&option=author&value=asdf


filter?open=true&role=authored&author=asdf(깃헙 아이디)
filter?open=true&role=authored&milestone=asdf(마일스톤 이름) 예: 1차_배포 -> “1차 배포”
filter?open=false&role=assigned&label=asdf(레이블 이름)
filter?open=false&role=commented&assignee=asdf(깃헙 아이디)

filter api 하에 다음의 파라미터가 있음.
open=true (opened) open=false(closed
role의 종류: authored, commented, assigned
세부 조건의 경우: author, assignee, milestone, label 를 마지막 쿼리 파라미터로 택일 하여 보낼 수 있음.
