### ISSUE TITLE
스토리보드 화면 연결

### ISSUE THREAD

**Issue by kjoonk** [codesquad-member-2020/issue-tracker-04#73]
필요한 화면(뷰컨트롤러)만 생성해서 앱 전반의 흐름 파악

- [x] 이슈 필터
- [x] 레이블 목록
- [x] 마일스톤 목록

@dev-Lena 레이블/마일스톤 작성 화면은 독립적인 뷰로 하는 게 어떨까 싶어요.

**Comment by dev-Lena** [comment]
> @dev-Lena 레이블/마일스톤 작성 화면은 독립적인 뷰로 하는 게 어떨까 싶어요.

네 좋아요! 
두 화면에서 사용할 수 있으니까 xib로 할까합니다!

**Comment by kjoonk** [comment]
> 두 화면에서 사용할 수 있으니까 xib로 할까합니다!

스토리보드로 처리했어요. 두 화면 중 같은 부분을 스토리보드로 만들고, 각 화면은 상속받아서 처리하려고 해요. 화면마다 달라지는 부분을 xib로 할 거에요.
