### ISSUE TITLE
이슈 목록 다중 선택 및 이동 구현

### ISSUE THREAD

**Issue by dev-Lena** [codesquad-member-2020/issue-tracker-04#8]
### 목록 화면
- [x] Edit 버튼 -> 선택화면일 경우 Cancel로 변경
- [x] Filter 버튼 -> Select All 로 변경

### 이슈 목록 State 관리
 - [x] 이슈 목록 TableView State에 따라 버튼 변경
  
### 선택 화면
- [x] 이슈 셀마다 check marker 활성화
- [x] 선택한 이슈의 개수 표시
- [x] `Select All` 버튼 탭할 경우 목록의 모든 이슈 선택(check marker 선택으로 표시)
- [x] 목록의 모든 이슈가 선택 됐을 경우 `Select All` 버튼이 `Deselect All`로 변경
- [x] `Deselect All` 버튼을 탭할 경우 목록의 모든 이슈 선택(check marker 선택으로 표시)
- [x] 선택한 이슈가 한 개 이상일 때 `선택 이슈 닫기(close selected issues)` 버튼 활성화
- [x] `선택 이슈 닫기(close selected issues)`버튼을 탭할 경우 선택된 이슈를 클로즈 (모델에서 삭제 + tableView에서 삭제)
-> merge 후 수정할 부분을 TODO로 남김

### 이슈 목록 - 이슈 순서 변경
- [x] Edit 버튼을 탭할 경우 이슈 셀 Edit 모드 활성화: 셀의 `reordering control` 활성화
- [x] `reordering control`로 이슈 셀 순서 재정렬
- [x] 순서 재정렬시 data source 및 tableview 에 적용

**Comment by kjoonk** [comment]
와.. 정말 세세하네요. 😲

**Comment by dev-Lena** [comment]
참고한 레퍼런스입니다! @kjoonk 

1. [TableView Multi Row Selection](https://medium.com/@mrachamallu/multiple-row-selection-with-check-buttons-for-uitableviewcells-programmatically-efb36507891) 참고한 자료입니다!

2. [tableView(_:shouldIndentWhileEditingRowAt:) Apple 문서](https://developer.apple.com/documentation/uikit/uitableviewdelegate/1614873-tableview)  입니다!

3. [Making table cells reorderable](https://www.ralfebert.de/ios-examples/uikit/uitableviewcontroller/reorderable-cells/) 참고한 자료입니다!

**Comment by dev-Lena** [comment]
리팩토링은 새로운 이슈 #30 로 관리합니다. 클로즈하겠습니다!
