### ISSUE TITLE
모델 상태 관리

### ISSUE THREAD

**Issue by kjoonk** [codesquad-member-2020/issue-tracker-04#9]
## 역할
모델의 상태를 관리하는 클래스. 객체간 모델 공유가 필요할 때 사용
- value 타입을 속성으로 가지는 클래스
- 모델을 사용하는 객체 간 상태를 공유
- 모델에 관련된 요청 및 응답 처리
- 이름: <Name>ModelController
- 기존의 StateController 대체
- 모델에 대해 share인지 local인지 고민해볼 것
  - share: 객체 간 상태 공유가 필요할 때. 참조가 필요할 때
  - local: 사용이 한정적일 때. 값 타입으로 넘겨도 상관없을 때. 예) 뷰에서 사용할 때

### User

- 로그인한 유저의 상태를 관리
- 앱 전반에서 공동으로 사용 -> SceneDelegate(?)에서 생성

### IssueList
- 이슈 목록 관리
- 로그인 후 첫 화면(메인 화면)에서 사용 -> SceneDelegate(?)에서 주입?

### Issue
- 단일 이슈 상태 관리
- IssueListViewController -> IssueDetailViewController

https://github.com/codesquad-member-2020/issue-tracker-04/issues/5#issuecomment-641188767

**Comment by kjoonk** [comment]
오늘 같이 진행했던 Collection 만들기에 관한 글이에요.
[Creating custom collections in Swift | Swift by Sundell](https://www.swiftbysundell.com/articles/creating-custom-collections-in-swift/)

**Comment by dev-Lena** [comment]
@kjoonk 올려주신 글 잘 읽었습니다!
### 읽은 소감
모스 덕분에 Collection 프로토콜을 준수하는 IssueCollection을 만들어서 구현하는 경험을 해봤네요! 
고민하면서 페어로 같이 구현해보고 글을 읽으니까 기존의 Collection이 어떻게 구현되어있는지, 그리고 제가 원하는 기능을 커스텀한 Collection에 추가하려면 어떤 관련 프로토콜을 채택해야하는지와 어떤 메소드를 수정/구현해야하는지 이해가 더 잘되서 좋았어요!! 감사합니다! 🤓
### 반영한 점
IssueStateController에서 CommentCollection을 이용해 commentedIssue를 가져오는 연산 프로퍼티와 테스트 코드 작성했습니다!

**Comment by kjoonk** [comment]
[Using Collections Effectively - WWDC 2018 - Videos - Apple Developer](https://developer.apple.com/videos/play/wwdc2018/229/): 이 영상을 통해 알게 되었어요. 시각적으로 이해할 수 있어 좋아요.
[(Swift) Array 완전 정복 - 03. Collection 프로토콜 · Wireframe](https://soooprmx.com/archives/7049): 한국어로 설명이 잘 되어 있는 블로그에요.
